# ---
# - name: Run the equivalent of "apt-get update" as a separate step
#   apt:
#     update_cache: yes

# - name: Install Mysql
#   apt: name=mysql update_cache=yes cache_valid_time=3600 state=present
    
# - name: Add .my.cnf
#   copy: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
      
# - name: update mysql root password for all root accounts  
#   mysql_user:  
#     name: root  
#     host: "{{ item }}"  
#     password: "snipeit1"  
#     login_user: root  
#     login_password: "snipeit1"  
#     check_implicit_admin: yes  
#     priv: "*.*:ALL,GRANT"  
#   with_items:  
#   - 192.168.33.20  
#   - 127.0.0.1  
#   - ::1  
#   - localhost



- name: Set the root password 
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1"

- name: Secure the root user for IPV6 localhost (::1)
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="::1"

- name: Secure the root user for IPV4 localhost (127.0.0.1)
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="127.0.0.1"

- name: Secure the root user for localhost domain
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="localhost"

- name: Secure the root user for server_hostname domain
  mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="10.10.10.14"

- name: Deletes anonymous server user
  mysql_user: login_user=root login_password="snipeit1" user="" host_all=yes state=absent

- name: Removes the test database
  mysql_db: login_user=root login_password="snipeit1" db=test state=absent




# ---

# - name: Run the equivalent of "apt-get update" as a separate step
#   apt:
#     update_cache: yes
    
# - name: Add .my.cnf
#   copy: src=my.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600
      
# - name: Set the root password 
#   mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1"

# - name: Secure the root user for IPV6 localhost (::1)
#   mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="::1"

# - name: Secure the root user for IPV4 localhost (127.0.0.1)
#   mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="127.0.0.1"

# - name: Secure the root user for localhost domain
#   mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="localhost"

# - name: Secure the root user for server_hostname domain
#   mysql_user: login_user=root login_password="snipeit1" user=root password="snipeit1" host="{{ ansible_fqdn }}"

# - name: Deletes anonymous server user
#   mysql_user: login_user=root login_password="snipeit1" user="" host_all=yes state=absent

# - name: Removes the test database
#   mysql_db: login_user=root login_password="snipeit1" db=test state=absent