---
  - name: Starting the installation processes
    hosts: all
    vars:
      ansible_python_interpreter: /usr/bin/python3
    become: true
    tasks: 
    - name: Update
      apt:
        update_cache: yes
    - include_tasks: apache2.yml
    - include_tasks: mariadb.yml
    - include_tasks: php.yml
    - include_tasks: pymysql.yml
    - include_tasks: my_sql.yml
    - include_tasks: setup_database.yml
    - include_tasks: composer.yml
    - include_tasks: git_clone_snipe.yml
    - include_tasks: composer_install.yml
    - include_tasks: www_data.yml
    - include_tasks: copy_files.yml
    - include_tasks: key_gen.yml
    - include_tasks: enable_snipeit.yml